#!/usr/bin/env python3
"""
Deployment Diagnostic: Is the cache fix actually deployed?
"""

import os
import sys

print("=" * 80)
print("DEPLOYMENT DIAGNOSTIC")
print("=" * 80)

# Check 1: What code is running?
print("\n1. CODE VERSION CHECK")
print("-" * 80)

# Read the actual deployed function
try:
    with open('src/models/climate_pipeline.py', 'r') as f:
        content = f.read()

    # Check for new signature without model_type
    if 'def _make_cache_key(self, language_code: str, base_query: str)' in content:
        print("✅ NEW CODE: _make_cache_key WITHOUT model_type parameter")
        print("   This is the FIXED version")
    elif 'def _make_cache_key(self, language_code: str, model_type: str, base_query: str)' in content:
        print("❌ OLD CODE: _make_cache_key WITH model_type parameter")
        print("   This is the BROKEN version - fix NOT deployed!")
    else:
        print("⚠️  UNKNOWN: Cannot find _make_cache_key function")

    # Check for the key material line
    if 'key_material = f"{language_code}:{base_query}"' in content:
        print("✅ Cache key format: language_code:query (CORRECT)")
    elif 'key_material = f"{language_code}:{model_type}:{base_query}"' in content:
        print("❌ Cache key format: language_code:model_type:query (BROKEN)")
    else:
        print("⚠️  Cannot determine cache key format")

except Exception as e:
    print(f"❌ Error reading file: {e}")

# Check 2: Git status
print("\n2. GIT STATUS")
print("-" * 80)
os.system('git log --oneline -1')
os.system('git status --short')

# Check 3: Environment
print("\n3. ENVIRONMENT")
print("-" * 80)
print(f"REDIS_HOST: {os.getenv('REDIS_HOST', 'NOT SET')}")
print(f"REDIS_PORT: {os.getenv('REDIS_PORT', 'NOT SET')}")
print(f"REDIS_SSL: {os.getenv('REDIS_SSL', 'NOT SET')}")
print(f"FORCE_COMMAND_A_RESPONSES: {os.getenv('FORCE_COMMAND_A_RESPONSES', 'NOT SET')}")

# Check 4: Can we import and test?
print("\n4. RUNTIME TEST")
print("-" * 80)
try:
    sys.path.insert(0, 'src')
    from models.climate_pipeline import ClimatePipeline

    # Check the signature
    import inspect
    sig = inspect.signature(ClimatePipeline._make_cache_key)
    params = list(sig.parameters.keys())

    print(f"Function signature: {params}")
    if 'model_type' in params:
        print("❌ RUNTIME: model_type parameter PRESENT (OLD CODE)")
    else:
        print("✅ RUNTIME: model_type parameter REMOVED (NEW CODE)")

    # Test actual key generation
    pipeline = ClimatePipeline.__new__(ClimatePipeline)
    test_key = pipeline._make_cache_key('en', 'what are the local impacts of climate change in toronto?')
    expected_key = 'q:en:41d95a83486a6ab486548d9f3c506a59568a6ebd7cb7d7a617e1177fdad915d7'

    print(f"\nGenerated key: {test_key}")
    print(f"Expected key:  {expected_key}")
    if test_key == expected_key:
        print("✅ KEY MATCH: Correct cache key generation")
    else:
        print("❌ KEY MISMATCH: Cache key generation is wrong!")

except Exception as e:
    print(f"❌ Runtime test failed: {e}")
    import traceback
    traceback.print_exc()

# Check 5: Redis connectivity
print("\n5. REDIS CONNECTION TEST")
print("-" * 80)
try:
    from models.redis_cache import ClimateCache
    cache = ClimateCache()
    if cache.redis_client:
        cache.redis_client.ping()
        print("✅ Redis connection: SUCCESS")

        # Count keys
        keys = cache.redis_client.keys('q:en:*')
        print(f"✅ Cache keys found: {len(keys)} English query keys")

        # Check for specific question
        test_key = 'q:en:41d95a83486a6ab486548d9f3c506a59568a6ebd7cb7d7a617e1177fdad915d7'
        exists = cache.redis_client.exists(test_key)
        if exists:
            ttl = cache.redis_client.ttl(test_key)
            print(f"✅ Specific question IS cached! TTL: {ttl}s ({ttl/60:.1f}m)")

            value = cache.redis_client.get(test_key)
            import json
            data = json.loads(value)
            model_type = data.get('model_type', 'unknown')
            print(f"   Generated by model_type: {model_type}")
        else:
            print(f"❌ Specific question NOT in cache")
            print(f"   Key: {test_key}")
            print(f"   Either never answered OR cache was cleared")
    else:
        print("❌ Redis client not initialized")
except Exception as e:
    print(f"❌ Redis test failed: {e}")

print("\n" + "=" * 80)
print("DIAGNOSIS SUMMARY")
print("=" * 80)
print("""
If you see:
✅ NEW CODE but ❌ question NOT in cache:
   → Code deployed but question needs to be answered once with new code
   → Ask the question again - it will cache with new key format

❌ OLD CODE:
   → Fix not deployed to production!
   → Need to deploy branch: claude/optimize-cache-new-users-011CUoRNpynPGjWyjBgtnV8A

✅ Everything but still cache miss:
   → Check application logs for actual error messages
   → May be skip_cache=True or cache initialization failing
""")
print("=" * 80)
