[server]
# Disable file watcher to prevent the Streamlit file watcher from
# triggering the "__path__._path" error with PyTorch internals
# Use valid keys supported by current Streamlit versions
fileWatcherType = "none"
runOnSave = false
enableCORS = true

[theme]
base = "light"
primaryColor = "#009376"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f6f6"
textColor = "#000000"
font = "sans serif"

[browser]
# Reduce memory footprint
gatherUsageStats = false

[logger]
level = "info"